stocks = {
    "AL2SI": "2CRSI",
    "AB": "AB Science",
    "ADOC": "Adocia",
    "ALAFY": "Afyren",
    "ALAGP": "Agripower",
    "ALAMG": "Auplata Mng Group",
    "ALTUV": "Bio-UV Group",
    "ALCLS": "Cellectis",
    "CGG": "CGG",
    "COV": "Covivio",
    "ALCJ": "Crossject",
    "ALCYB": "Cybergun",
    "ALDBT": "DBT",
    "ALDMS": "DMS",
    "ALDRV": "Drone Volt",
    "ALESA": "Ecoslops",
    "ALENE": "Enertime",
    "EXN": "Exclusive Networks",
    "FALG": "Fermentalg",
    "ALGEC": "GECI INTL",
    "GNFT": "Genfit",
    "ALGEN": "Genoway",
    "SIGHT": "Gensight Biolo",
    "ALGBE": "Global Bioenergies",
    "ALHGR": "Hoffmann Green Cement Tec",
    "ALHYG": "Hybrigenics",
    "ALKLA": "Klarsen",
    "LIN": "Linedata Services",
    "MC": "LVMH",
    "MEMS": "Memscap Regpt",
    "ALTHO": "Metavisio",
    "METEX": "Metabolic Explorer",
    "ALNFL": "NFL Biosciences",
    "ALORD": "Ordissimo",
    "ALRPD": "Rapid Nutri",
    "SOI": "Soitec",
    "S30": "Solutions 30",
    "SQI": "SQLI",
    "ALTME": "TME Pharma",
    "VANTI": "Vantiva",
    "ALVER": "Vergnet",
    "ALUVI": "UV Germi",
    "VLA": "Valneva",
    "VANTI": "Vantiva",
    "VMX": "Verimatrix",
    "WAGA": "Waga Energies",
    "XIL": "Xilam Animation",
}

stocks_test = {
    "AL2SI": "2CRSI",
    "AB": "AB Science",
    "ADOC": "Adocia",
    "CGG": "CGG",
    "COV": "Covivio",
    "ALCJ": "Crossject"
}